version: '3'
services:
  compiler:
    build: mvncompiler
    volumes:
      - type: volume
        source: java-war
        target: /root/result/
  production:
    image: tomcat:9.0-jdk14
    volumes:
      - type: volume
        source: java-war
        target: /usr/local/tomcat/webapps/
    depends_on:
      - compiler
volumes:
  java-war:
