version: '3'
services:
  compiler:
    build: mvncompiler
    volumes:
      - ./target:/root/boxfuse-sample/target/
  production:
    image: tomcat:9.0.20-jre8-alpine
    volumes:
      - ./target/hello-1.0.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - compiler
