version: '3'
services:
  compiler:
    build: mvncompiler
    volumes:
      - type: volume
        source: java-war
        target: /root/boxfuse-sample-master/target
  production:
    image: tomcat:9.0-jdk14
    volumes:
      - type: volume
        source: java-war
        target: /root/boxfuse-sample-master/target
    command: cp /root/boxfuse-sample/target-master/hello-1.0.war /usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - compiler
volumes:
  java-war:
